openapi: 3.0.1
info:
  description: The API of the Item Relationship Service (IRS) for retrieving item
    graphs along the value chain of CATENA-X partners.
  title: IRS API
  version: "1.0"
servers:
- url: http://irs.int.demo.catena-x.net
paths:
  /irs/jobs:
    get:
      description: Returns jobIds for requested job states.
      operationId: getJobIdsByJobStates
      parameters:
      - description: Requested job states.
        explode: false
        in: query
        name: jobStates
        required: false
        schema:
          type: array
          items:
            type: string
            enum:
            - UNSAVED
            - INITIAL
            - RUNNING
            - TRANSFERS_FINISHED
            - COMPLETED
            - CANCELED
            - ERROR
      responses:
        "200":
          content:
            application/json:
              examples:
                complete:
                  $ref: '#/components/examples/complete-job-list-processing-state'
              schema:
                type: array
                items:
                  type: string
                  format: uuid
          description: Array of jobIds for requested job states.
        "404":
          content:
            application/json:
              examples:
                complete:
                  $ref: '#/components/examples/error-response'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: No jobIds found for requested job states.
      summary: Returns jobIds for requested job states.
      tags:
      - Item Relationship Service
    post:
      description: "Register an IRS job to retrieve an item graph for given {globalAssetId}."
      operationId: registerJobForGlobalAssetId
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterJob'
        required: true
      responses:
        "201":
          content:
            application/json:
              examples:
                complete:
                  $ref: '#/components/examples/job-handle'
              schema:
                $ref: '#/components/schemas/JobHandle'
          description: Returns jobId of registered job.
        "400":
          content:
            application/json:
              examples:
                complete:
                  $ref: '#/components/examples/error-response'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Job registration failed.
      summary: "Register an IRS job to retrieve an item graph for given {globalAssetId}."
      tags:
      - Item Relationship Service
  /irs/jobs/{jobId}:
    get:
      description: Return job with optional item graph result for requested jobId.
      operationId: getJobForJobId
      parameters:
      - description: JobId of the job.
        example: 6c311d29-5753-46d4-b32c-19b918ea93b0
        in: path
        name: jobId
        required: true
        schema:
          type: string
          format: uuid
          maxLength: 36
          minLength: 36
      - description: "<true> Return job with current processed item graph. <false>\
          \ Return job with item graph if job is in state <COMPLETED>, otherwise job."
        in: query
        name: returnUncompletedJob
        required: false
        schema:
          type: boolean
          default: true
      responses:
        "200":
          content:
            application/json:
              examples:
                complete:
                  $ref: '#/components/examples/complete-job-result'
              schema:
                $ref: '#/components/schemas/Jobs'
          description: Return job with item graph for the requested jobId.
        "206":
          content:
            application/json:
              examples:
                complete:
                  $ref: '#/components/examples/partial-job-result'
              schema:
                $ref: '#/components/schemas/Jobs'
          description: Return job with current processed item graph for the requested
            jobId.
        "404":
          content:
            application/json:
              examples:
                complete:
                  $ref: '#/components/examples/error-response'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Job with the requested jobId not found.
      summary: Return job with optional item graph result for requested jobId.
      tags:
      - Item Relationship Service
    put:
      description: Cancel job for requested jobId.
      operationId: cancelJobByJobId
      parameters:
      - description: JobId of the job.
        example: 6c311d29-5753-46d4-b32c-19b918ea93b0
        in: path
        name: jobId
        required: true
        schema:
          type: string
          format: uuid
          maxLength: 36
          minLength: 36
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Job'
          description: Job with requested jobId canceled.
        "404":
          content:
            application/json:
              examples:
                complete:
                  $ref: '#/components/examples/error-response'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Job for requested jobId not found.
      summary: Cancel job for requested jobId.
      tags:
      - Item Relationship Service
components:
  examples:
    canceled-job-result:
      value:
        job:
          createdOn: 2022-02-03T14:48:54.709Z
          exception:
            errorDetail: Timeout while requesting Digital Registry
            exception: IrsTimeoutException
            exceptionDate: 2022-02-03T14:48:54.709Z
          globalAssetId: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          jobCompleted: 2022-02-03T14:48:54.709Z
          jobId: e5347c88-a921-11ec-b909-0242ac120002
          jobState: CANCELED
          lastModifiedOn: 2022-02-03T14:48:54.709Z
          owner: ""
          queryParameter:
            aspects:
            - SerialPartTypization
            - Contact
            bomLifecycle: asBuilt
            depth: 4
            direction: downward
          requestUrl: https://api.server.test/api/../
          startedOn: 2022-02-03T14:48:54.709Z
          summary:
            asyncFetchedItems:
              complete: 0
              failed: 0
              queue: 0
              running: 0
        relationships: []
        tombstones: []
    complete-job-list-processing-state:
      value:
      - 6c311d29-5753-46d4-b32c-19b918ea93b0
    complete-job-result:
      value:
        job:
          createdOn: 2022-02-03T14:48:54.709Z
          exception:
            errorDetail: Timeout while requesting Digital Registry
            exception: IrsTimeoutException
            exceptionDate: 2022-02-03T14:48:54.709Z
          globalAssetId: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          jobCompleted: 2022-02-03T14:48:54.709Z
          jobId: e5347c88-a921-11ec-b909-0242ac120002
          jobState: COMPLETED
          lastModifiedOn: 2022-02-03T14:48:54.709Z
          owner: ""
          queryParameter:
            aspects:
            - SerialPartTypization
            - Contact
            bomLifecycle: asBuilt
            depth: 4
            direction: downward
          requestUrl: https://api.server.test/api/../
          startedOn: 2022-02-03T14:48:54.709Z
          summary:
            asyncFetchedItems:
              complete: 0
              failed: 0
              queue: 0
              running: 0
        relationships:
        - catenaXId: urn:uuid:d9bec1c6-e47c-4d18-ba41-0a5fe8b7f447
          childItem:
            assembledOn: 2022-02-03T14:48:54.709Z
            childCatenaXId: urn:uuid:a45a2246-f6e1-42da-b47d-5c3b58ed62e9
            lastModifiedOn: 2022-02-03T14:48:54.709Z
            lifecycleContext: asBuilt
            quantity:
              measurementUnit:
                datatypeURI: urn:bamm:io.openmanufacturing:meta-model:1.0.0#piece
                lexicalValue: piece
              quantityNumber: 1
        shells:
        - descriptions:
          - language: en
            text: The shell for a vehicle
          globalAssetIds:
          - urn:uuid:a45a2246-f6e1-42da-b47d-5c3b58ed62e9
          idShort: future concept x
          identification: 882fc530-b69b-4707-95f6-5dbc5e9baaa8
          specificAssetIds:
            engineserialid: "12309481209312"
          submodelDescriptors:
          - descriptions:
            - language: en
              text: Provides base vehicle information
            endpoints:
            - interfaceType: HTTP
              protocolInformation:
                endpointAddress: https://catena-x.net/vehicle/basedetails/
                endpointProtocol: HTTPS
                enpointProtocolVersion: "1.0"
            idShort: vehicle base details
            identification: 4a738a24-b7d8-4989-9cd6-387772f40565
            semanticId:
              values:
              - urn:bamm:com.catenax.vehicle:0.1.1
          - descriptions:
            - language: en
              text: Provides base vehicle information
            endpoints:
            - interfaceType: HTTP
              protocolInformation:
                endpointAddress: https://catena-x.net/vehicle/partdetails/
                endpointProtocol: HTTPS
                enpointProtocolVersion: "1.0"
            idShort: vehicle part details
            identification: dae4d249-6d66-4818-b576-bf52f3b9ae90
            semanticId:
              values:
              - urn:bamm:com.catenax.vehicle:0.1.1#PartDetails
        tombstones:
        - catenaXId: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          endpointURL: https://catena-x.net/vehicle/partdetails/
          processingError:
            errorDetail: Details to reason of Failure
            lastAttempt: 2022-02-03T14:48:54.709Z
            retryCounter: 0
    error-response:
      value:
        errors:
        - TimeoutException
        - ParsingException
        message: Some errors occurred
        statusCode: 500 INTERNAL_SERVER_ERROR
    failed-job-result:
      value:
        job:
          createdOn: 2022-02-03T14:48:54.709Z
          exception:
            errorDetail: Timeout while requesting Digital Registry
            exception: IrsTimeoutException
            exceptionDate: 2022-02-03T14:48:54.709Z
          globalAssetId: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          jobId: e5347c88-a921-11ec-b909-0242ac120002
          jobState: ERROR
          lastModifiedOn: 2022-02-03T14:48:54.709Z
          owner: ""
          queryParameter:
            aspects:
            - SerialPartTypization
            - Contact
            bomLifecycle: asBuilt
            depth: 4
            direction: downward
          requestUrl: https://api.server.test/api/../
          startedOn: 2022-02-03T14:48:54.709Z
          summary:
            asyncFetchedItems:
              complete: 0
              failed: 0
              queue: 0
              running: 0
        relationships: []
        tombstones: []
    job-handle:
      value:
        jobId: 6c311d29-5753-46d4-b32c-19b918ea93b0
    job-result-without-uncompleted-result-tree:
      value:
        job:
          createdOn: 2022-02-03T14:48:54.709Z
          exception:
            errorDetail: Timeout while requesting Digital Registry
            exception: IrsTimeoutException
            exceptionDate: 2022-02-03T14:48:54.709Z
          globalAssetId: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          jobCompleted: 2022-02-03T14:48:54.709Z
          jobId: e5347c88-a921-11ec-b909-0242ac120002
          jobState: COMPLETED
          lastModifiedOn: 2022-02-03T14:48:54.709Z
          owner: ""
          queryParameter:
            aspects:
            - SerialPartTypization
            - Contact
            bomLifecycle: asBuilt
            depth: 4
            direction: downward
          requestUrl: https://api.server.test/api/../
          startedOn: 2022-02-03T14:48:54.709Z
          summary:
            asyncFetchedItems:
              complete: 0
              failed: 0
              queue: 0
              running: 0
        relationships:
        - catenaXId: urn:uuid:d9bec1c6-e47c-4d18-ba41-0a5fe8b7f447
          childItem:
            assembledOn: 2022-02-03T14:48:54.709Z
            childCatenaXId: urn:uuid:a45a2246-f6e1-42da-b47d-5c3b58ed62e9
            lastModifiedOn: 2022-02-03T14:48:54.709Z
            lifecycleContext: asBuilt
            quantity:
              measurementUnit:
                datatypeURI: urn:bamm:io.openmanufacturing:meta-model:1.0.0#piece
                lexicalValue: piece
              quantityNumber: 1
        shells:
        - descriptions:
          - language: en
            text: The shell for a vehicle
          globalAssetIds:
          - urn:uuid:a45a2246-f6e1-42da-b47d-5c3b58ed62e9
          idShort: future concept x
          identification: 882fc530-b69b-4707-95f6-5dbc5e9baaa8
          specificAssetIds:
            engineserialid: "12309481209312"
          submodelDescriptors:
          - descriptions:
            - language: en
              text: Provides base vehicle information
            endpoints:
            - interfaceType: HTTP
              protocolInformation:
                endpointAddress: https://catena-x.net/vehicle/basedetails/
                endpointProtocol: HTTPS
                enpointProtocolVersion: "1.0"
            idShort: vehicle base details
            identification: 4a738a24-b7d8-4989-9cd6-387772f40565
            semanticId:
              values:
              - urn:bamm:com.catenax.vehicle:0.1.1
          - descriptions:
            - language: en
              text: Provides base vehicle information
            endpoints:
            - interfaceType: HTTP
              protocolInformation:
                endpointAddress: https://catena-x.net/vehicle/partdetails/
                endpointProtocol: HTTPS
                enpointProtocolVersion: "1.0"
            idShort: vehicle part details
            identification: dae4d249-6d66-4818-b576-bf52f3b9ae90
            semanticId:
              values:
              - urn:bamm:com.catenax.vehicle:0.1.1#PartDetails
        tombstones:
        - catenaXId: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          endpointURL: https://catena-x.net/vehicle/partdetails/
          processingError:
            errorDetail: Details to reason of Failure
            lastAttempt: 2022-02-03T14:48:54.709Z
            retryCounter: 0
    partial-job-result:
      value:
        job:
          createdOn: 2022-02-03T14:48:54.709Z
          exception:
            errorDetail: Timeout while requesting Digital Registry
            exception: IrsTimeoutException
            exceptionDate: 2022-02-03T14:48:54.709Z
          globalAssetId: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          jobCompleted: 2022-02-03T14:48:54.709Z
          jobId: e5347c88-a921-11ec-b909-0242ac120002
          jobState: RUNNING
          lastModifiedOn: 2022-02-03T14:48:54.709Z
          owner: ""
          queryParameter:
            aspects:
            - SerialPartTypization
            - Contact
            bomLifecycle: asBuilt
            depth: 4
            direction: downward
          requestUrl: https://api.server.test/api/../
          startedOn: 2022-02-03T14:48:54.709Z
          summary:
            asyncFetchedItems:
              complete: 0
              failed: 0
              queue: 0
              running: 0
        relationships: []
        tombstones: []
  schemas:
    AsyncFetchedItems:
      type: object
      description: Statistics of job execution.
      properties:
        complete:
          type: integer
          format: int32
          description: Number of completed item transfers.
        failed:
          type: integer
          format: int32
          description: Number of failed item transfers.
        queue:
          type: integer
          format: int32
          description: Number of item transfers remaining.
        running:
          type: integer
          format: int32
          description: Number of running item transfers.
    ChildItem:
      type: object
      description: Set of child parts the parent object is assembled by (one structural
        level down).
      properties:
        assembledOn:
          type: string
          format: date-time
          description: Datetime of assembly.
        childCatenaXId:
          $ref: '#/components/schemas/GlobalAssetIdentification'
        lastModifiedOn:
          type: string
          format: date-time
          description: Last datetime item was modified.
        lifecycleContext:
          type: string
          description: The lifecycle context in which the child part was assembled
            into the parent part.
          enum:
          - asBuilt
        quantity:
          $ref: '#/components/schemas/Quantity'
    Description:
      type: object
      description: Provide descriptions to request parts.
      properties:
        language:
          type: string
          description: Language used for description.
          example: en
          maxLength: 3
        text:
          type: string
          description: Description text.
          example: The shell for a vehicle
          maxLength: 4000
    Endpoint:
      type: object
      description: Communication endpoint.
      properties:
        interfaceType:
          type: string
          default: HTTP
          description: Communication interface type.
          example: HTTP
        protocolInformation:
          $ref: '#/components/schemas/ProtocolInformation'
    ErrorResponse:
      type: object
      description: Error response.
      properties:
        errors:
          type: array
          description: List of errors.
          items:
            type: string
            description: List of errors.
        message:
          type: string
          description: Error message.
        statusCode:
          type: string
          description: Error code.
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
    GlobalAssetIdentification:
      type: object
      description: CATENA-X global asset id in the format urn:uuid:<uuid>.
      properties:
        globalAssetId:
          type: string
          description: CATENA-X global asset id in the format urn:uuid:<uuid>.
          example: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          maxLength: 45
          minLength: 45
    Job:
      type: object
      description: Executable unit with meta information and item graph result.
      properties:
        action:
          type: string
          description: HTTP verbs used by request.
        createdOn:
          type: string
          format: date-time
        exception:
          $ref: '#/components/schemas/JobErrorDetails'
        globalAssetId:
          $ref: '#/components/schemas/GlobalAssetIdentification'
        jobCompleted:
          type: string
          format: date-time
        jobId:
          type: string
          format: uuid
          description: JobId of the job.
          maxLength: 36
          minLength: 36
        jobState:
          type: string
          enum:
          - UNSAVED
          - INITIAL
          - RUNNING
          - TRANSFERS_FINISHED
          - COMPLETED
          - CANCELED
          - ERROR
        lastModifiedOn:
          type: string
          format: date-time
        owner:
          type: string
          description: The IRS api consumer.
        queryParameter:
          $ref: '#/components/schemas/QueryParameter'
        requestUrl:
          type: string
          format: url
        startedOn:
          type: string
          format: date-time
        summary:
          $ref: '#/components/schemas/Summary'
      required:
      - globalAssetId
      - jobId
      - jobState
    JobErrorDetails:
      type: object
      description: Job error details.
      properties:
        errorDetail:
          type: string
          description: Detailed exception information.
          maxLength: 4000
        exception:
          type: string
          description: Exception name.
          maxLength: 100
        exceptionDate:
          type: string
          format: date-time
          description: Datetime error occurs.
    JobHandle:
      type: object
      properties:
        jobId:
          type: string
          format: uuid
    Jobs:
      type: object
      description: Container for a job with item graph.
      properties:
        job:
          $ref: '#/components/schemas/Job'
        relationships:
          type: array
          description: Relationships between parent and child items.
          items:
            $ref: '#/components/schemas/Relationship'
        shells:
          type: array
          description: AAS shells.
          items:
            $ref: '#/components/schemas/Shell'
        tombstones:
          type: array
          description: Collection of not resolvable endpoints as tombstones. Including
            cause of error and endpoint URL.
          items:
            $ref: '#/components/schemas/Tombstone'
    MeasurementUnit:
      type: object
      properties:
        datatypeURI:
          type: string
        lexicalValue:
          type: string
    ProcessingError:
      type: object
      properties:
        errorDetail:
          type: string
        lastAttempt:
          type: string
          format: date-time
        retryCounter:
          type: integer
          format: int32
    ProtocolInformation:
      type: object
      description: Information to the interface used.
      properties:
        endpointAddress:
          type: string
          format: uri
          description: Uniform resource identifier of endpoint.
          example: https://catena-x.net/vehicle/basedetails/
        endpointProtocol:
          type: string
          description: Protocol used to access the endpoint.
          example: HTTP or HTTPS
        enpointProtocolVersion:
          type: string
          description: Protocol version.
          example: "1.0"
    Quantity:
      type: object
      description: Quantity component.
      properties:
        measurementUnit:
          $ref: '#/components/schemas/MeasurementUnit'
        quantityNumber:
          type: integer
          format: int32
    QueryParameter:
      type: object
      description: Query parameter for current irs query.
      properties:
        aspects:
          type: string
          enum:
          - SerialPartTypization
          - AssemblyPartRelationship
          - PartDimension
          - SupplyRelationData
          - PCFCoreData
          - PCFTechnicalData
          - MarketPlaceOffer
          - MaterialAspect
          - BatteryPass
          - ProductDescriptionVehicle
          - ProductDescriptionBattery
          - ReturnRequest
          - CertificateOfDestruction
          - CertificateOfDismantler
          - Address
          - Contact
        bomLifecycle:
          type: string
          description: The lifecycle context in which the child part was assembled
            into the parent part.
          enum:
          - asBuilt
        depth:
          type: integer
          format: int32
        direction:
          type: string
          description: Item graph traversal direction.
          enum:
          - downward
    RegisterJob:
      type: object
      description: The requested job definition.
      properties:
        aspects:
          type: array
          items:
            type: string
            enum:
            - SerialPartTypization
            - AssemblyPartRelationship
            - PartDimension
            - SupplyRelationData
            - PCFCoreData
            - PCFTechnicalData
            - MarketPlaceOffer
            - MaterialAspect
            - BatteryPass
            - ProductDescriptionVehicle
            - ProductDescriptionBattery
            - ReturnRequest
            - CertificateOfDestruction
            - CertificateOfDismantler
            - Address
            - Contact
        bomLifecycle:
          type: string
          description: The lifecycle context in which the child part was assembled
            into the parent part.
          enum:
          - asBuilt
        depth:
          type: integer
          format: int32
          description: Max depth of the item graph returned. If no depth is set item
            graph with max depth is returned.
          maximum: 100
          minimum: 1
        direction:
          type: string
          default: downward
          description: Item graph traversal direction.
          enum:
          - downward
        globalAssetId:
          type: string
          description: Id of global asset.
          example: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          maxLength: 45
          minLength: 45
          pattern: "^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      required:
      - globalAssetId
    Relationship:
      type: object
      description: Relationships between parent and child items.
      properties:
        catenaXId:
          $ref: '#/components/schemas/GlobalAssetIdentification'
        childItem:
          $ref: '#/components/schemas/ChildItem'
        parentItem:
          $ref: '#/components/schemas/ChildItem'
    SemanticId:
      type: object
      properties:
        values:
          type: array
          items:
            type: string
    Shell:
      type: object
      description: AAS shells.
      properties:
        descriptions:
          type: array
          items:
            $ref: '#/components/schemas/Description'
        globalAssetIds:
          type: array
          items:
            $ref: '#/components/schemas/GlobalAssetIdentification'
        idShort:
          type: string
        identification:
          type: string
        specificAssetIds:
          type: object
          additionalProperties:
            type: string
        submodelDescriptors:
          type: array
          items:
            $ref: '#/components/schemas/SubmodelDescriptor'
    SubmodelDescriptor:
      type: object
      properties:
        descriptions:
          type: array
          items:
            $ref: '#/components/schemas/Description'
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/Endpoint'
        idShort:
          type: string
        identification:
          type: string
        semanticId:
          $ref: '#/components/schemas/SemanticId'
    Summary:
      type: object
      description: Summary of the job with statistics of the job processing.
      properties:
        asyncFetchedItems:
          $ref: '#/components/schemas/AsyncFetchedItems'
    Tombstone:
      type: object
      description: Collection of not resolvable endpoints as tombstones. Including
        cause of error and endpoint URL.
      properties:
        catenaXId:
          type: string
        endpointURL:
          type: string
        processingError:
          $ref: '#/components/schemas/ProcessingError'
